version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn my_project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=my_project.settings
