version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: yourdatabase
      DATABASE_USER: youruser
      DATABASE_PASSWORD: yourpassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
