# Generated by Django 4.2.11 on 2024-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название школы')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Субъект РФ')),
                ('locality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населенный пункт')),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('number_of_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество учащихся')),
                ('school_type', models.CharField(blank=True, choices=[('public', 'Государственная'), ('private', 'Частная'), ('charter', 'Чартерная')], max_length=50, null=True, verbose_name='Тип школы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Логотип')),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО заполнителя заявки')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон заполнителя заявки')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail заполнителя заявки')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
    ]
