# Generated by Django 5.0.6 on 2024-07-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название школы'),
        ),
    ]
