# Generated by Django 4.2.11 on 2024-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('declined', 'Отказано учеником')], default='pending', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_send', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Заявка регистрации на олимпиаду',
                'verbose_name_plural': 'Заявки регистрации на олимпиады',
            },
        ),
        migrations.CreateModel(
            name='RegisterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_admin', models.BooleanField(default=False, verbose_name='Статус администратора')),
                ('status_teacher', models.BooleanField(default=False, verbose_name='Статус учителя')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_teacher', models.BooleanField(default=False, verbose_name='Статус учителя')),
                ('status_admin', models.BooleanField(default=False, verbose_name='Статус администратора')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('status_send', models.BooleanField(default=False, verbose_name='Статус отправки')),
            ],
        ),
    ]
