# Generated by Django 5.1a1 on 2024-06-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_remove_register_admin_olympiad_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_send', models.BooleanField(default=False)),
                ('Olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ученик', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Заявка регистрации на олимпиаду',
                'verbose_name_plural': 'Заявки регистрации на олимпиады',
            },
        ),
        migrations.CreateModel(
            name='Register_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_admin', models.BooleanField(default=False)),
                ('status_teacher', models.BooleanField(default=False)),
                ('Olympiad_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_admin', to='main.olympiad')),
                ('child_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_admin', to=settings.AUTH_USER_MODEL)),
                ('teacher_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Register_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_teacher', models.BooleanField(default=False)),
                ('status_admin', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status_send', models.BooleanField(default=False)),
                ('Olympiad_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_send', to='main.olympiad')),
                ('child_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_send', to=settings.AUTH_USER_MODEL)),
                ('teacher_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_send')),
            ],
            options={
                'unique_together': {('teacher_send', 'child_send', 'Olympiad_send')},
            },
        ),
    ]
