# Generated by Django 4.2.11 on 2024-08-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
        ('register', '0001_initial'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersend',
            name='child_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registersend',
            name='olympiad_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_send', to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='registersend',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_register_send', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='registersend',
            name='teacher_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель отправитель'),
        ),
        migrations.AddField(
            model_name='registeradmin',
            name='child_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeradmin',
            name='olympiad_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_admin', to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='registeradmin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_register_admin', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='registeradmin',
            name='teacher_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель администратор'),
        ),
        migrations.AddField(
            model_name='register',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ученик', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_register', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_recommendation', to='school.school'),
        ),
        migrations.AlterUniqueTogether(
            name='registersend',
            unique_together={('teacher_send', 'child_send', 'olympiad_send')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('recommended_by', 'recommended_to', 'child', 'olympiad')},
        ),
    ]
