# Generated by Django 5.1a1 on 2024-06-08 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_register_admin_olympiad_admin_and_more'),
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_child', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to=settings.AUTH_USER_MODEL)),
                ('recommended_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
