# Generated by Django 4.2.11 on 2024-07-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_send',
            name='child_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register_send',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_register_send', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='register_send',
            name='teacher_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_send'),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='Olympiad_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_admin', to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='child_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_register_admin', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='teacher_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_admin'),
        ),
        migrations.AddField(
            model_name='register',
            name='Olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ученик', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_register', to='school.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='Olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_recommendation', to='school.school'),
        ),
        migrations.AlterUniqueTogether(
            name='register_send',
            unique_together={('teacher_send', 'child_send', 'Olympiad_send')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('recommended_by', 'recommended_to', 'child', 'Olympiad')},
        ),
    ]
