# Generated by Django 5.1a1 on 2024-06-08 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_register_admin_olympiad_admin_and_more'),
        ('register', '0002_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('recommended_by', 'recommended_to', 'child', 'Olympiad')},
        ),
    ]
