# Generated by Django 4.2.11 on 2024-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_send',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=5),
            preserve_default=False,
        ),
    ]
