# Generated by Django 4.2.11 on 2024-07-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('register', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register_send',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_register_send', to='school.school', verbose_name='Школа'),
        ),
    ]
