# Generated by Django 4.2.11 on 2024-07-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('register', '0003_register_is_deleted_alter_register_send_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_recommendation', to='school.school'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('declined', 'Отказано учеником')], default='pending', max_length=20),
        ),
    ]
