# Generated by Django 4.2.11 on 2024-07-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_recommendation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_send',
            name='is_deleted',
        ),
    ]
