# Generated by Django 4.2.11 on 2024-07-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_created_at_recommendation_created_at_recommendation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='created_at_recommendation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='register_admin',
            name='created_at_admin',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='created_at_send',
        ),
    ]
