# Generated by Django 4.2.11 on 2024-07-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_created_at_recommendation_recommendation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
    ]
