# Generated by Django 4.2.11 on 2024-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register_send_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_admin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
