# Generated by Django 4.2.11 on 2024-05-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='info_children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Информация об ученике'),
        ),
        migrations.AddField(
            model_name='result',
            name='info_olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad', verbose_name='Информация об олимпиаде'),
        ),
        migrations.AddField(
            model_name='register_send',
            name='Olympiad_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_send', to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register_send',
            name='child_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register_send',
            name='teacher_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_send'),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='Olympiad_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_admin', to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='child_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register_admin',
            name='teacher_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher_admin'),
        ),
        migrations.AddField(
            model_name='register',
            name='Olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.olympiad'),
        ),
        migrations.AddField(
            model_name='register',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ученик', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='category',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='level',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='main.level_olympiad', verbose_name='Название уровня'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='stage',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='main.stage', verbose_name='Название этапа'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Название школьного предмета'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='Child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
