# Generated by Django 5.0.6 on 2024-07-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Level_olympiad',
            new_name='LevelOlympiad',
        ),
    ]
