# Generated by Django 4.2.11 on 2024-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
    ]
