# Generated by Django 5.0.2 on 2024-03-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_send',
            old_name='Register',
            new_name='Register_send_str',
        ),
        migrations.AddField(
            model_name='register',
            name='status_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register_send',
            name='status_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Register_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_admin', models.BooleanField(default=False)),
                ('Register_admin_str', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Register_admin', to='main.register_send')),
            ],
        ),
    ]
