# Generated by Django 5.0.6 on 2024-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_send',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
