# Generated by Django 4.2.11 on 2024-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='Выпустился'),
        ),
    ]
