# Generated by Django 4.2.11 on 2024-07-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='time',
        ),
    ]
