# Generated by Django 4.2.11 on 2024-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroom_is_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
