# Generated by Django 5.0.6 on 2024-06-05 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_register_send_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_admin',
            name='Register_admin_str',
        ),
        migrations.AlterUniqueTogether(
            name='register_send',
            unique_together={('teacher_send', 'child_send', 'Olympiad_send')},
        ),
        migrations.AddField(
            model_name='register_send',
            name='status_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='Register_send_str',
        ),
    ]
