# Generated by Django 5.0.2 on 2024-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_rename_register_register_send_register_send_str_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategory',
            new_name='categories',
        ),
    ]
