# Generated by Django 4.2.11 on 2024-07-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('main', '0003_olympiad_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_olympiad', to='school.school', verbose_name='Школа'),
        ),
    ]
