# Generated by Django 5.0.2 on 2024-04-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_сategory_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_send',
            name='Register_send_str',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Register', to='main.register'),
        ),
        migrations.AlterField(
            model_name='register_send',
            name='status_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
