# Generated by Django 5.0.6 on 2024-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_classroomapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_admin',
            name='status_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ClassroomApplication',
        ),
    ]
