# Generated by Django 5.0.2 on 2024-04-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_alter_register_send_register_send_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_send',
            name='Register_send_str',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Register',
                                    to='main.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_send',
            name='status_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
