# Generated by Django 4.2.11 on 2024-07-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('main', '0005_alter_olympiad_options_remove_olympiad_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'verbose_name': 'Олимпиада', 'verbose_name_plural': 'Олимпиады'},
        ),
        migrations.AddField(
            model_name='olympiad',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='class_olympiad',
            field=models.IntegerField(verbose_name='Класс олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level_olympiad', verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Место проведения олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_olympiad', to='school.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stage', verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Название школьного предмета'),
        ),
    ]
