# Generated by Django 4.2.11 on 2024-07-01 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_actionlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionLog',
            new_name='AuditLog',
        ),
    ]
