# Generated by Django 5.0.2 on 2024-04-02 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_register_send_register_send_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_send',
            name='Register_send_str',
        ),
        migrations.DeleteModel(
            name='Register_admin',
        ),
        migrations.DeleteModel(
            name='Register_send',
        ),
    ]
