# Generated by Django 4.2.11 on 2024-07-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_olympiad_options_olympiad_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='school',
        ),
        migrations.RemoveField(
            model_name='level_olympiad',
            name='school',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='school',
        ),
        migrations.RemoveField(
            model_name='post',
            name='school',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
