# Generated by Django 4.2.11 on 2024-07-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_actionlog_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='next_stage',
        ),
    ]
