# Generated by Django 4.2.11 on 2024-07-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_olympiad_next_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level_olympiad', verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Место проведения олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stage', verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
    ]
