# Generated by Django 5.0.2 on 2024-04-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_remove_register_send_register_send_str_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_teacher', models.BooleanField(default=False)),
                ('Register_send_str',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Register',
                                   to='main.register')),
            ],
        ),
        migrations.CreateModel(
            name='Register_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_admin', models.BooleanField(default=False)),
                ('Register_admin_str',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Register_admin',
                                   to='main.register_send')),
            ],
        ),
    ]
