# Generated by Django 5.1a1 on 2024-06-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_register_send_status_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_admin',
            name='Olympiad_admin',
        ),
        migrations.RemoveField(
            model_name='register_admin',
            name='child_admin',
        ),
        migrations.RemoveField(
            model_name='register_admin',
            name='teacher_admin',
        ),
        migrations.AlterUniqueTogether(
            name='register_send',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='Olympiad_send',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='child_send',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='teacher_send',
        ),
        migrations.RemoveField(
            model_name='result',
            name='info_children',
        ),
        migrations.RemoveField(
            model_name='result',
            name='info_olympiad',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Register_admin',
        ),
        migrations.DeleteModel(
            name='Register_send',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
