# Generated by Django 5.0.6 on 2024-06-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_register_admin_olympiad_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_olympiads', to='main.stage', verbose_name='Следующий этап'),
        ),
    ]
