# Generated by Django 5.0.2 on 2024-04-02 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_register_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='register_send',
            name='Olympiad_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Olympiad_send', to='main.olympiad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_send',
            name='child_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_send', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_send',
            name='teacher_send',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_send', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='register_send',
            name='Register_send_str',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Register', to='main.register'),
        ),
    ]
