# Generated by Django 5.0.2 on 2024-04-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_register_send_olympiad_send_register_send_child_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='Olympiad_send',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='child_send',
        ),
        migrations.RemoveField(
            model_name='register_send',
            name='teacher_send',
        ),
        migrations.AlterField(
            model_name='register_send',
            name='Register_send_str',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Register',
                                    to='main.register'),
            preserve_default=False,
        ),
    ]
