# Generated by Django 5.0.2 on 2024-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_register_send_register_send_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_send',
            name='Register_send_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
