# Generated by Django 5.0.2 on 2024-04-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_register_admin_olympiad_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_admin',
            name='Register_admin_str',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Register_admin', to='main.register_send'),
        ),
    ]
