# Generated by Django 4.2.11 on 2024-07-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cropping',
        ),
    ]
