# Generated by Django 4.2.11 on 2024-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram ID'),
        ),
    ]
