# Generated by Django 4.2.11 on 2024-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expelled',
            field=models.BooleanField(default=False, verbose_name='Исключен'),
        ),
    ]
